#!/bin/bash
#
# name		: ddclient_C-IP
# desciption	: ddclient WANIP compare and updatescript
# autor		: Speefak ( itoss@gmx.de )
# licence	: (CC) BY-NC-SA by speefak
# version	: 1.2
# infosource	: https://ssl.tiggerswelt.net/wiki/ddns/ddclient
#
#------------------------------------------------------------------------------------------------------------
############################################################################################################
#######################################   define global variables   ########################################
############################################################################################################
#------------------------------------------------------------------------------------------------------------

 HostAddress1=<DDNSDomain1>
#HostAddress2=<DDNSDomain2>
#HostAddress3=

 WANIP=$(wget -q -O - http://www.nwlab.net/cgi-bin/show-ip-js | cut -d'>' -f2 | cut -d '<' -f 1 | sed -ne '2p')

#WANIP=$(wget -q -O - https://check.torproject.org | grep "Your IP address appears to be:" | cut -d ">" -f2 | cut -d "<" -f1)           # HTTPS yes                     # HTTPS no
#WANIP=$(wget -q -O - checkip.dyndns.org|sed -e 's/.*Current IP Address: //' -e 's/<.*$//')                                             # HTTPS no

#------------------------------------------------------------------------------------------------------------
############################################################################################################
###########################################   define functions   ###########################################
############################################################################################################
#------------------------------------------------------------------------------------------------------------
gethostip () {
	ActualIP=$(nslookup $DynDnsAddress | tr -d ':' | cut -f5 | grep Address | cut -c9-23) 
}
#------------------------------------------------------------------------------------------------------------
compare_ips () {
	if   [ "$WANIP" == "$ActualIP" ] ; then
		echo
		echo "$WANIP => actual WAN IP"
		echo "$ActualIP => $DynDnsAddress IP"
		echo
		echo " IP not changed - Do nothing ... "

	else
		echo
		echo "$WANIP => actual WAN IP"
		echo "$ActualIP => $DynDnsAddress IP"
		echo
		echo " IP CHANGED AND NOT UPDATED TO $DynDnsAddress"
		echo
		echo "starting ddnclient"
		echo
		echo "IP changed on $(date) from $ActualIP to $WANIP ($HOSTNAME)" | mail -s "IP CHANGE for  => $DynDnsAddress <=  to $WANIP ($HOSTNAME)" root
		rm -f /var/cache/ddclient/ddclient.cache
		sudo ddclient --force
	fi
}
#-------------------------------------------------------------------------------------------------------------------------------------------------------
############################################################################################################
#############################################   start script   #############################################
############################################################################################################
#------------------------------------------------------------------------------------------------------------

	# check for root permission
if [ "$(whoami)" = "root" ]; then echo "";else printf "$LRed Are You Root ?\n";exit 1;fi

#------------------------------------------------------------------------------------------------------------

 for HostAddress in $(cat $0 | grep "HostAddress[[:digit:]]=" | grep -v "^#") ; do
	DynDnsAddress=$( cut -d "=" -f2-10 <<< "$HostAddress")
	gethostip
	compare_ips
 done

#------------------------------------------------------------------------------------------------------------

exit 0




# Configuration file for ddclient generated by debconf
#
# /etc/ddclient.conf

#daemon=300
verbose=no
ssl=yes
use=web
use=if, if=eno1
web=checkip.spdns.de
protocol=dyndns2
server=update.spdyn.de

## First Domain
login=<DDNSUser>
password=<DDNSPass>
<DDNSDomain1>






